In [4]:
import numpy as np

In [5]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])

In [6]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [48]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

In [60]:
a_centered = np.subtract(a, mean_a)
a_centered


array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [61]:
a_centered_t = a_centered.T
a_centered_t

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [62]:
a1 = a_centered_t [0]
a2 = a_centered_t [1]

In [70]:
a_centered_sp = a1 @ a2

In [71]:
a_centered_sp 

8.0

In [72]:
a_centered_sp / (5-1)

2.0

In [73]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])